export interface LlmConfig {
  model: string;
  /** Temperature for the analysis model or general model */
  temperature: number;
  /** Optional model used to analyze descriptions generated by the vision model */
  analysis_model?: string;
  /** Temperature for the vision model when applicable */
  vision_temperature?: number;
  /** Prompt used for generating frame descriptions */
  prompt?: string;
  /** Additional context about the video for the models */
  context?: string;
}

